### ISSUE TITLE
CSS: percentage keyframes are not highlighted

### ISSUE THREAD

**Issue by igor-gorohovsky** [pustota-theme/pustota#30]
Code example:
```css
@keyframes bounce {
  0% {
    transform: translateY(0);
  }
  20% {
    transform: translateY(-10px);
  }
  50% {
    transform: translateY(-5px);
  }
  100% {
    transform: translateY(0);
  }
}
```
Actual:
![Image](https://github.com/user-attachments/assets/ee06561d-5f0c-41e5-990c-eb2e907c2fe3)

Expected: 
![Image](https://github.com/user-attachments/assets/c40675ef-a381-43eb-b01f-70d4c40014ba)
